# Generated by Django 5.1.1 on 2024-09-24 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('selling_price', models.FloatField()),
                ('discounted_price', models.FloatField()),
                ('description', models.TextField(default='')),
                ('prodapp', models.TextField(default='')),
                ('category', models.CharField(choices=[('PL', 'Pencil'), ('PX', 'Pencil Box'), ('PN', 'Pencil'), ('RR', 'Ruler'), ('RN', 'Ruled Note'), ('UN', 'UnRuledNote'), ('ER', 'Eraser'), ('SR', 'Sharpener')], max_length=2)),
                ('Product_image', models.ImageField(upload_to='product')),
            ],
        ),
    ]
